// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/analytics" | "/admin/customers" | "/admin/inventory" | "/admin/orders" | "/admin/reports" | "/auth/forgot-password" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/auth/unauthorized" | "/auth/verify" | "/brands" | "/cart" | "/checkout" | "/collections" | "/collections/[collection]" | "/collections/children" | "/collections/lifestyle" | "/collections/men" | "/collections/sneakers" | "/collections/women" | "/eco" | "/inventory/live-dashboard" | "/inventory/notifications" | "/login" | "/loyalty" | "/order/success" | "/orders" | "/privacy" | "/products" | "/products/[slug]" | "/profile" | "/register" | "/showcase" | "/test-stripe" | "/vendor" | "/vendor/analytics" | "/vendor/inventory" | "/vendor/products" | "/vendor/products/new" | "/wishlist"
type AppRouteHandlerRoutes = "/api/admin/create-stock-function" | "/api/admin/migrate-stock-functions" | "/api/cron/cleanup-reservations" | "/api/debug/stripe" | "/api/inventory/alerts" | "/api/inventory/live-dashboard" | "/api/inventory/movements" | "/api/inventory/notifications" | "/api/inventory/stock" | "/api/inventory/stock/batch" | "/api/inventory/test" | "/api/orders/create-from-payment" | "/api/placeholder/[...path]" | "/api/products/[id]/sizes" | "/api/products/[id]/stock" | "/api/products/[id]/variants" | "/api/stock/reservations" | "/api/stock/reservations/bulk" | "/api/stock/reservations/cleanup" | "/api/stock/reservations/validate" | "/api/stripe/create-payment-intent" | "/api/stripe/update-payment-intent" | "/api/stripe/webhook" | "/api/test-products" | "/api/test-stock-decrement" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/customers": {}
  "/admin/inventory": {}
  "/admin/orders": {}
  "/admin/reports": {}
  "/api/admin/create-stock-function": {}
  "/api/admin/migrate-stock-functions": {}
  "/api/cron/cleanup-reservations": {}
  "/api/debug/stripe": {}
  "/api/inventory/alerts": {}
  "/api/inventory/live-dashboard": {}
  "/api/inventory/movements": {}
  "/api/inventory/notifications": {}
  "/api/inventory/stock": {}
  "/api/inventory/stock/batch": {}
  "/api/inventory/test": {}
  "/api/orders/create-from-payment": {}
  "/api/placeholder/[...path]": { "path": string[]; }
  "/api/products/[id]/sizes": { "id": string; }
  "/api/products/[id]/stock": { "id": string; }
  "/api/products/[id]/variants": { "id": string; }
  "/api/stock/reservations": {}
  "/api/stock/reservations/bulk": {}
  "/api/stock/reservations/cleanup": {}
  "/api/stock/reservations/validate": {}
  "/api/stripe/create-payment-intent": {}
  "/api/stripe/update-payment-intent": {}
  "/api/stripe/webhook": {}
  "/api/test-products": {}
  "/api/test-stock-decrement": {}
  "/auth/callback": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/auth/unauthorized": {}
  "/auth/verify": {}
  "/brands": {}
  "/cart": {}
  "/checkout": {}
  "/collections": {}
  "/collections/[collection]": { "collection": string; }
  "/collections/children": {}
  "/collections/lifestyle": {}
  "/collections/men": {}
  "/collections/sneakers": {}
  "/collections/women": {}
  "/eco": {}
  "/inventory/live-dashboard": {}
  "/inventory/notifications": {}
  "/login": {}
  "/loyalty": {}
  "/order/success": {}
  "/orders": {}
  "/privacy": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/profile": {}
  "/register": {}
  "/showcase": {}
  "/test-stripe": {}
  "/vendor": {}
  "/vendor/analytics": {}
  "/vendor/inventory": {}
  "/vendor/products": {}
  "/vendor/products/new": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
